version: '2.1'
services:
   mysql:
     image: mysql/mysql-server:5.7
     environment:
       - MYSQL_DATABASE="stu"
       - MYSQL_ROOT_PASSWORD="root"
       - MYSQL_ROOT_HOST='%'
     restart: always
     volumes:
       - /var/app/nho_db:/var/lib/mysql
   app:
     restart: always
     image: java
     working_dir: /app
     volumes:
       - /var/app/:/app
     ports:
       - "0.0.0.0:9000:8888"
     links:
       - mysql
     command: java -jar /app/app.jar

